import "./scss/style.scss";
import "./scss/normalize.css";
import "./scss/fonts.css";
import game from "./js/game";
import "./js/move";
import newHeight from "./js/falling-bird";
import "./js/blockGenerator";

let height = 300;
height = newHeight(height);
console.log(height);
height = newHeight(height);
console.log(height);
height = newHeight(height);
console.log(height);
height = newHeight(height);
console.log(height);
height = newHeight(height);
console.log(height);
height = newHeight(height);
console.log(height);
console.log("---------------------");
height = newHeight(height, true);
console.log(height);
height = newHeight(height, true);
console.log(height);
height = newHeight(height, true);
console.log(height);
